version: '3.8'
services:
  # app:
  #   container_name: kaidemy_be
  #   #Dev mode
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
   
  #   # depends_on:
  #   #   - db
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
    # networks:
    #   - app_db

  db:
    container_name: kaidemy_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: kaidemy
      POSTGRES_USER: kaidemy
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - app_db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
   
  # redis:
  #   container_name: nestjs_boilerplate_redis
  #   image: redis:7-alpine
  #   restart: always
  #   command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
  #   ports:
  #     - $REDIS_HOST_PORT:$REDIS_PORT
  #   volumes:
  #     - .docker/redis:/data
  #   networks:
  #     - app_redis
volumes:
  postgres_data:
# networks:
#   app_db:
  # app_redis: